/**
 * Generates src/environments/environment.prod.ts before production builds.
 * Set on Vercel: API_URL=https://your-api.onrender.com
 * Optional: SOCKET_URL, GOOGLE_CLIENT_ID
 */
const fs = require('fs');
const path = require('path');

function normalizeApiUrl(raw) {
  let url = (raw || 'http://localhost:3000').trim().replace(/\/$/, '');
  if (!url.endsWith('/api')) {
    url += '/api';
  }
  return url;
}

if (process.env.VERCEL && !process.env.API_URL) {
  console.error('ERROR: Set API_URL in Vercel (e.g. https://indiahouse.onrender.com)');
  process.exit(1);
}

const apiUrl = normalizeApiUrl(process.env.API_URL);
const socketUrl = (process.env.SOCKET_URL || apiUrl.replace(/\/api$/, '')).replace(/\/$/, '');
const googleClientId =
  process.env.GOOGLE_CLIENT_ID ||
  '1021134306283-igdic6fv5o89jo3io59thuhgiiipntg4.apps.googleusercontent.com';

const outPath = path.join(__dirname, '../src/environments/environment.prod.ts');
const content = `// Auto-generated by scripts/generate-env.js — do not edit manually
export const environment = {
  production: true,
  apiUrl: '${apiUrl}',
  socketUrl: '${socketUrl}',
  googleClientId: '${googleClientId}'
};
`;

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, content, 'utf8');
console.log('Generated environment.prod.ts');
console.log('  apiUrl:', apiUrl);
console.log('  socketUrl:', socketUrl);
