// Auto-generated by scripts/generate-env.js — do not edit manually
export const environment = {
  production: true,
  apiUrl: 'http://localhost:3000/api',
  socketUrl: 'http://localhost:3000',
  googleClientId: '1021134306283-igdic6fv5o89jo3io59thuhgiiipntg4.apps.googleusercontent.com'
};
